name: TimeAndDate
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display Current Date
        run: |

          echo "Current date and time: $(date +%H:%M:%S %d/%m/%y)"
